### ISSUE TITLE
FanDuel MLB: Only a handful of lineups generated

### ISSUE THREAD

**Issue by EdCarGoes** [DimaKudosh/pydfs-lineup-optimizer#259]
Hi there,
I'm trying to test this tool (It's amazing by the way) to generate 150 FanDuel MLB lineups. I am feeding it players from a .csv that has 121 players and their projections. I'm not restricting it with any rules. Literally just here's the players, optimize top 150. So the most basic usage possible. But it will only deliver 75 lineups and then it errors with "Unable to build lineup." There should be way more than enough players to generate 150 lineups. I'll attach my .csv resource and paste the code below. Am I doing something wrong?

dfinfopath = 'path to .csv reference'

optimizer = get_optimizer(Site.FANDUEL, Sport.BASEBALL)
optimizer.load_players_from_csv(dfinfopath)

count = 0
for lineup in optimizer.optimize(150):
    count = count + 1
    print(count)
    print(lineup)

[fd_reference.zip](https://github.com/DimaKudosh/pydfs-lineup-optimizer/files/6259023/fd_reference.zip)

**Comment by bigboyz** [comment]
I been trying to figure this out since April 1.  FanDuel is breaking for me constantly for Baseball only.  I believe the problem has to do with multiple positions available.  All the other modules have no problem with the multiple positions, but FanDuel keeps throwing errors after a few lineups.

This is where the magic stops happening:


495         players_with_positions = link_players_with_positions(players, positions)
--
496         for player, position in players_with_positions.items():
497             lineup.append(LineupPlayer(player, position.name, used_fppg=context.players_used_fppg.get(player)))
players_with_positions undefined, global link_players_with_positions = <function link_players_with_positions>, players = [Frankie Montas P (OAK), Christian Yelich OF (MIL), Keston Hiura 1B/2B (MIL), Aaron Judge OF (NYY), Mike Trout OF (LAA), Austin Meadows OF (TB), Anthony Rendon 3B (LAA), Kevin Kiermaier OF (TB), Bo Bichette SS (TOR)], positions = [<pydfs_lineup_optimizer.settings.LineupPosition object>, <pydfs_lineup_optimizer.settings.LineupPosition object>, <pydfs_lineup_optimizer.settings.LineupPosition object>, <pydfs_lineup_optimizer.settings.LineupPosition object>, <pydfs_lineup_optimizer.settings.LineupPosition object>, <pydfs_lineup_optimizer.settings.LineupPosition object>, <pydfs_lineup_optimizer.settings.LineupPosition object>, <pydfs_lineup_optimizer.settings.LineupPosition object>, <pydfs_lineup_optimizer.settings.LineupPosition object>]

Been banging my head against the wall trying to figure out who or what is causing this and no luck yet.

**Comment by EdCarGoes** [comment]
Interesting. I thought it might be the multiple positions too, but I am getting some players in my generated lineups who are eligible at multiple positions. But maybe that can still happen while it's messing up the results. I'm not sure and kind of lost.

**Comment by bigboyz** [comment]
Same here.  It works until it doesn't than throws the error.  The CSV file always populates, but I have never reached 150.  Usually dies between 10-40 lineups.  It handles the multiple positions for some, but the players_with_positions error shows undefined.

My thought was maybe it chooses Player X to be a C/1B, but then it fails when player X is OF.  It also fails every time if you set exposure in FanDuel.Baseball.  You can't generate a lineup if you set min or max exposure in FanDuel baseball, so maybe the key is somewhere there too.

**Comment by EdCarGoes** [comment]
Ok I have no idea what happened but I just ran the exact same minimalistic code with the exact same .csv file and it gave me a full 150. What in the world? What would be dynamically changing throughout the day? @bigboyz see if yours works now?

**Comment by bigboyz** [comment]
No dice.  Same errors for me.  What slate are you using on FanDuel?  I'm failing with #56543 the main for tonight at 7:05PM EST

**Comment by EdCarGoes** [comment]
Yes I'm running main slate too. I did upgrade my pydfs_lineup_optimmizer module this morning. Maybe there was some caching issue that didn't clear itself until later in the day? Have you run an upgrade recently?

**Comment by lightninglarry** [comment]
im following to see if u guys come up with results.

**Comment by bigboyz** [comment]
Ahhh...I didn't see a new version was released yesterday.  Going to try that.  I'll update later today when I got it downloaded.

**Comment by DimaKudosh** [comment]
It was a bug with multi positions for FD MLB, I fixed it and released new version 3.4.2

**Comment by tlabropoulos** [comment]
> Ahhh...I didn't see a new version was released yesterday. Going to try that. I'll update later today when I got it downloaded.

@bigboyz  were you able to get this resolved? On latest code and seem to still be having an issue here with this.

**Comment by mbencho** [comment]
I am also having trouble with this but can't seem to pin down the issue other than it seems to be happening when there are players with more than two positions. for example when a player has C/1B/2B as a position the optimizer may create a set of lineups but stop before it should with no explanation. But if I remove all the players with three positions then it will calculate the appropriate set of lineups

**Comment by tlabropoulos** [comment]
@DimaKudosh it looks like this is still an issue, even in the latest version. 

It seems to mostly be an issue when the player has three eligible positions, and it looks like it's bugging out during the link_players_with_positions part. It also looks like C1B and SS positions are causing the issue. Can't confirm this 100%.

If you trim all players to 2 positions, the issue settles down a lot but still fails on a few. If you trim down to a single position per player, the issue disappears. 

"LineupOptimizerException: Unable to build lineup”

Appreciate any help you can provide.

**Comment by madkap7** [comment]
@bigboyz @mbencho were you guys able to get this resolved? Having same issue.
